import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../../auth/AuthProvider";
import { supabase } from "../../lib/supabase";
import { useCourses } from "./CourseProvider";
import { uid, type BlockKind, type Course, type LessonBlock } from "./types";

const palette: { kind: BlockKind; icon: string; title: string; hint: string }[] = [
  {kind:"text",icon:"T",title:"Текст",hint:"Текст и инструкции"},{kind:"video",icon:"▶",title:"Видео",hint:"YouTube, MP4, WebM и другие форматы"},{kind:"audio",icon:"♫",title:"Аудио",hint:"MP3, WAV, OGG и другие форматы"},{kind:"quiz",icon:"✓",title:"Задание",hint:"Вопрос и варианты ответов"},{kind:"html",icon:"</>",title:"HTML-код",hint:"Встраиваемый HTML"},{kind:"file",icon:"↥",title:"Файл",hint:"Ссылка на PDF, PPT или документ"},
];
const makeBlock = (kind: BlockKind): LessonBlock => ({ id: uid(), kind, title: palette.find(x=>x.kind===kind)!.title, content: kind === "quiz" ? "Какой вариант правильный?\nПравильный ответ\nДругой ответ" : "" });

export function CourseEditorPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const { canEditCourses, user } = useAuth(); const store = useCourses();
  const source = store.courses.find(x => x.id === params.get("course"));
  const savedCourseRef=useRef<Course|null>(source?structuredClone(source):null);
  const [course, setCourse] = useState<Course | null>(source || null); const [moduleId,setModuleId]=useState(source?.modules[0]?.id || ""); const [lessonId,setLessonId]=useState(source?.modules[0]?.lessons[0]?.id || ""); const [selected,setSelected]=useState(""); const [dragging,setDragging]=useState<string|null>(null); const [dropTarget,setDropTarget]=useState<{id:string;edge:"before"|"after"}|null>(null); const [saved,setSaved]=useState(true); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [uploadError,setUploadError]=useState(""); const [preview,setPreview]=useState(false);
  const [paletteWidth,setPaletteWidth]=useState(()=>Math.min(460,Math.max(280,Number(localStorage.getItem("lingvaedu-editor-palette-width"))||310))); const [paletteResize,setPaletteResize]=useState<{startX:number;startWidth:number}|null>(null);
  useEffect(()=>{if(!paletteResize)return;const clamp=(value:number)=>Math.min(460,Math.max(280,value));const move=(event:PointerEvent)=>setPaletteWidth(clamp(paletteResize.startWidth+paletteResize.startX-event.clientX));const stop=(event:PointerEvent)=>{const width=clamp(paletteResize.startWidth+paletteResize.startX-event.clientX);setPaletteWidth(width);localStorage.setItem("lingvaedu-editor-palette-width",String(width));setPaletteResize(null);};document.body.classList.add("resizingEditorPalette");window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop,{once:true});return()=>{document.body.classList.remove("resizingEditorPalette");window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop);};},[paletteResize]);
  useEffect(() => {
    if (course || !source) return;
    const timer = window.setTimeout(() => {
      setCourse(source);
      savedCourseRef.current=structuredClone(source);
      setModuleId(source.modules[0]?.id || "");
      setLessonId(source.modules[0]?.lessons[0]?.id || "");
    }, 0);
    return () => window.clearTimeout(timer);
  }, [course, source]);
  const module = course?.modules.find(x=>x.id===moduleId) || course?.modules[0]; const lesson = module?.lessons.find(x=>x.id===lessonId) || module?.lessons[0]; const block = lesson?.blocks.find(x=>x.id===selected);
  const mutate = (fn:(draft:Course)=>Course) => { if(course){setCourse(fn(structuredClone(course)));setSaved(false);} };
  const updateLesson = (patch: object) => mutate(c=>({...c,modules:c.modules.map(m=>m.id===module?.id?{...m,lessons:m.lessons.map(l=>l.id===lesson?.id?{...l,...patch}:l)}:m)}));
  const updateBlocks = (blocks:LessonBlock[]) => updateLesson({blocks});
  const addModule=()=>mutate(c=>{const id=uid(),lid=uid();setModuleId(id);setLessonId(lid);return {...c,modules:[...c.modules,{id,title:`Модуль ${c.modules.length+1}`,lessons:[{id:lid,title:"Новый урок",description:"",timeLimit:0,attempts:0,blocks:[]}]}]}});
  const addLesson=()=>{if(!module)return;const id=uid();setLessonId(id);mutate(c=>({...c,modules:c.modules.map(m=>m.id===module.id?{...m,lessons:[...m.lessons,{id,title:"Новый урок",description:"",timeLimit:0,attempts:0,blocks:[]}]}:m)}));};
  const addBlock=(kind:BlockKind)=>{const b=makeBlock(kind);updateBlocks([...(lesson?.blocks||[]),b]);setSelected(b.id);};
  const reorder=(fromId:string,targetId:string,edge:"before"|"after")=>{if(!lesson||fromId===targetId)return;const next=[...lesson.blocks];const from=next.findIndex(x=>x.id===fromId);const target=next.findIndex(x=>x.id===targetId);if(from<0||target<0)return;const [item]=next.splice(from,1);const insert=next.findIndex(x=>x.id===targetId)+(edge==="after"?1:0);next.splice(insert,0,item);updateBlocks(next);};
  const uploadMedia=async(file:File)=>{if(!block||!lesson||!course||!supabase||!user)return;setUploading(true);setUploadError("");try{const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${user.id}/${course.id}/${uid()}-${safeName}`;const {error}=await supabase.storage.from("course-media").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const {data}=supabase.storage.from("course-media").getPublicUrl(path);updateBlocks(lesson.blocks.map(x=>x.id===block.id?{...x,content:data.publicUrl}:x));}catch(error){setUploadError(error instanceof Error?error.message:"Не удалось загрузить файл");}finally{setUploading(false);}};
  const save=async()=>{if(course && !saved && !saving){setSaving(true);try{await store.saveCourse(course);savedCourseRef.current=structuredClone(course);setSaved(true);}finally{setSaving(false);}}};
  const cancelChanges=()=>{const snapshot=savedCourseRef.current;if(!snapshot||saving)return;const restored=structuredClone(snapshot);const activeModule=restored.modules.find(item=>item.id===moduleId)||restored.modules[0];const activeLesson=activeModule?.lessons.find(item=>item.id===lessonId)||activeModule?.lessons[0];setCourse(restored);setModuleId(activeModule?.id||"");setLessonId(activeLesson?.id||"");setSelected("");setUploadError("");setSaved(true);};
  const rendered=useMemo(()=>lesson?.blocks||[],[lesson?.blocks]);
  if(!canEditCourses) return <main className="content"><div className="courseEmpty"><h2>Нет доступа к редактору</h2><button className="btn primary" onClick={()=>navigate("/courses")}>К курсам</button></div></main>;
  if(!course) return <main className="content"><div className="courseEmpty"><h2>Курс не найден</h2><button className="btn primary" onClick={()=>navigate("/courses")}>К списку курсов</button></div></main>;
  return <main className="editorPage courseEditor fade">
    <div className="editorTop"><button className="backBtn" onClick={()=>navigate("/courses")}>←</button><div className="courseIdentity"><small>НАЗВАНИЕ КУРСА</small><input aria-label="Название курса" className="courseTitleInput" value={course.title} placeholder="Введите название курса" onChange={e=>mutate(c=>({...c,title:e.target.value}))}/><b>{lesson?.title||"Добавьте урок"}</b></div><div className="saveState"><i className={saved?"saved":""}/>{saving?"Сохраняем изменения…":saved?"Все изменения сохранены":"Есть несохранённые изменения"}</div><select className="courseLanguageSelect" aria-label="Язык курса" title="Язык курса" value={course.language} onChange={e=>mutate(c=>({...c,language:e.target.value}))}><option>Английский</option><option>Русский</option><option>Казахский</option><option>Корейский</option><option>Китайский</option><option>Японский</option></select><select className={`courseColorSelect ${course.color}`} aria-label="Цвет обложки" title="Цвет обложки" value={course.color} onChange={e=>mutate(c=>({...c,color:e.target.value}))}><option value="purple">Фиолетовый</option><option value="blue">Синий</option><option value="green">Зелёный</option><option value="orange">Оранжевый</option><option value="pink">Розовый</option><option value="dark">Тёмный</option></select><select className="publishSelect" value={course.status} onChange={e=>mutate(c=>({...c,status:e.target.value as Course["status"]}))}><option value="draft">Черновик</option><option value="published">Опубликован</option><option value="archived">Архив</option></select><button className={`btn previewUndoButton ${saved?"previewMode":"undoMode"}`} disabled={saving} onClick={()=>saved?setPreview(true):cancelChanges()} aria-label={saved?"Открыть предпросмотр":"Отменить несохранённые изменения"}><span key={saved?"preview":"undo"}>{saved?"Предпросмотр":"↶ Отменить"}</span></button><button className="btn primary saveCourseButton" disabled={saved || saving} onClick={save}>{saving?"Сохраняем…":saved?"Сохранено":"Сохранить"}</button></div>
    <div className="editorLayout" style={{"--palette-width":`${paletteWidth}px`} as CSSProperties}><aside className="lessonTree"><div className="treeHead"><span>СОДЕРЖАНИЕ КУРСА</span><button onClick={addModule}>＋</button></div>{course.modules.map((m,mi)=><div className="module" key={m.id}><div className="moduleEdit"><small>МОДУЛЬ {mi+1}</small><input value={m.title} onChange={e=>mutate(c=>({...c,modules:c.modules.map(x=>x.id===m.id?{...x,title:e.target.value}:x)}))}/><button onClick={()=>{setModuleId(m.id);addLesson()}}>＋</button></div>{m.lessons.map((l,li)=><button key={l.id} className={`treeLesson ${lesson?.id===l.id?"active":""}`} onClick={()=>{setModuleId(m.id);setLessonId(l.id);setSelected("")}}><i>{li+1}</i><span>{l.title}<small>{l.blocks.length} блоков</small></span></button>)}</div>)}<button className="addModule" onClick={addModule}>＋ Добавить модуль</button></aside>
    <section className="canvas"><div className="canvasHead"><div><span>УРОК</span><input value={lesson?.title||""} onChange={e=>updateLesson({title:e.target.value})}/><textarea value={lesson?.description||""} onChange={e=>updateLesson({description:e.target.value})} placeholder="Описание урока"/></div><div className="lessonSettings"><label>Лимит, мин<input type="number" min="0" value={lesson?.timeLimit||0} onChange={e=>updateLesson({timeLimit:+e.target.value})}/></label><label>Попытки<input type="number" min="0" value={lesson?.attempts||0} onChange={e=>updateLesson({attempts:+e.target.value})}/></label></div></div><div className="blockCanvas">{lesson?.blocks.map((b)=><article key={b.id} className={`lessonBlock ${selected===b.id?"selected":""} ${dragging===b.id?"dragging":""} ${dropTarget?.id===b.id&&dragging!==b.id?(dropTarget.edge==="before"?"dropBefore":"dropAfter"):""}`} onClick={()=>setSelected(b.id)} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="move";const rect=e.currentTarget.getBoundingClientRect();const edge=e.clientY<rect.top+rect.height/2?"before":"after";if(dropTarget?.id!==b.id||dropTarget.edge!==edge)setDropTarget({id:b.id,edge})}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropTarget(current=>current?.id===b.id?null:current)}} onDrop={e=>{e.preventDefault();if(dragging&&dropTarget)reorder(dragging,dropTarget.id,dropTarget.edge);setDragging(null);setDropTarget(null)}}><span className="drag" draggable title="Перетащить блок" aria-label="Перетащить блок" onDragStart={e=>{e.stopPropagation();e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",b.id);setDragging(b.id)}} onDragEnd={()=>{setDragging(null);setDropTarget(null)}}>⋮⋮</span><div className={`blockGlyph ${b.kind==="media"?"video":b.kind}`}>{palette.find(p=>p.kind===(b.kind==="media"?"video":b.kind))?.icon}</div><div><b>{b.title}</b><p>{palette.find(p=>p.kind===(b.kind==="media"?"video":b.kind))?.hint}</p></div><div className="blockActions"><button aria-label="Удалить блок" title="Удалить блок" onClick={e=>{e.stopPropagation();updateBlocks(lesson.blocks.filter(x=>x.id!==b.id))}}>×</button></div></article>)}{!lesson?.blocks.length&&<div className="emptyCanvas">Выберите блок справа, чтобы начать собирать урок.</div>}</div></section>
    <div className="paletteResizer" role="separator" aria-orientation="vertical" aria-label="Изменить ширину панели блоков" title="Потяните, чтобы изменить ширину" onPointerDown={event=>{event.preventDefault();setPaletteResize({startX:event.clientX,startWidth:paletteWidth});}}><span/></div><aside className="blockPalette"><div><span>{block?"НАСТРОЙКА БЛОКА":"БЛОКИ"}</span><p>{block?"Изменения применяются сразу":"Добавьте блок в урок"}</p></div>{block?<div className="blockInspector"><label>Название<input value={block.title} onChange={e=>updateBlocks(lesson!.blocks.map(x=>x.id===block.id?{...x,title:e.target.value}:x))}/></label><label>{block.kind==="video"||block.kind==="media"?"Ссылка на YouTube или видео":block.kind==="audio"?"Ссылка на аудио":"Содержимое"}{block.kind==="text"||block.kind==="quiz"||block.kind==="html"?<textarea rows={12} value={block.content} onChange={e=>updateBlocks(lesson!.blocks.map(x=>x.id===block.id?{...x,content:e.target.value}:x))}/>:<input type="url" placeholder={block.kind==="audio"?"https://.../audio.mp3":"https://youtube.com/watch?v=..."} value={block.content} onChange={e=>updateBlocks(lesson!.blocks.map(x=>x.id===block.id?{...x,content:e.target.value}:x))}/>}</label>{(block.kind==="video"||block.kind==="media"||block.kind==="audio")&&<div className="mediaUploader"><span>ИЛИ ЗАГРУЗИТЕ ФАЙЛ</span><label className={uploading?"uploading":""}>↥ <b>{uploading?"Загрузка…":block.kind==="audio"?"Выбрать аудиофайл":"Выбрать видеофайл"}</b><small>{block.kind==="audio"?"MP3, WAV или OGG":"MP4, WebM или MOV"}</small><input type="file" disabled={uploading} accept={block.kind==="audio"?"audio/mpeg,audio/wav,audio/ogg,audio/mp4":"video/mp4,video/webm,video/quicktime"} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadMedia(file)}}/></label>{uploadError&&<p className="uploadError">{uploadError}</p>}{block.content&&<p className="mediaReady">✓ Материал добавлен</p>}</div>}<button className="btn ghost" onClick={()=>setSelected("")}>Готово</button></div>:palette.map(p=><button key={p.kind} onClick={()=>addBlock(p.kind)}><i className={p.kind}>{p.icon}</i><span><b>{p.title}</b><small>{p.hint}</small></span><em>＋</em></button>)}</aside></div>
    {preview&&<div className="courseModal" onClick={()=>setPreview(false)}><div onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setPreview(false)}>×</button><small>{course.title}</small><h1>{lesson?.title}</h1><p>{lesson?.description}</p>{rendered.map(b=><section className="previewBlock" key={b.id}><h3>{b.title}</h3>{b.kind==="html"?<div className="htmlPreview">HTML-код скрыт в безопасном предпросмотре</div>:b.kind==="audio"?<audio controls src={b.content}/>:b.kind==="video"||b.kind==="media"?<video className="lessonVideo" controls src={b.content}/>:b.kind==="file"?<a href={b.content} target="_blank" rel="noreferrer">Открыть материал →</a>:b.kind==="quiz"?<div>{b.content.split("\n").map((x,i)=>i===0?<b key={i}>{x}</b>:<label key={i}><input type="radio" name={b.id}/>{x}</label>)}</div>:<p>{b.content}</p>}</section>)}</div></div>}
  </main>;
}
